# Generated by Django 3.0.7 on 2020-07-06 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200702_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_user',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
