# Generated by Django 3.0.7 on 2020-07-07 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_followed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_user',
        ),
        migrations.AddField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
