# Generated by Django 3.0.7 on 2020-07-06 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200704_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='card',
            name='favorite_of',
            field=models.ManyToManyField(blank=True, related_name='favorite_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
