# Generated by Django 3.0.7 on 2020-07-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200707_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(default='C_ONE', max_length=25),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(default='F_ONE', max_length=25),
        ),
    ]
